[package]
name = "mapreduce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.12.0"
assert_cmd = "2.0.4"

# standard crate data is left out
[dev-dependencies]
pretty_assertions = "1"
